# Generated by Django 4.1.1 on 2023-01-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=50, verbose_name='технология'),
        ),
    ]
